# (spoken text for TTS, caption text shown on screen)
SEG=[
("Ahoi! Ich bin Käpt'n Kurt. Heute erzähle ich dir die Geschichte der Titanic, des berühmtesten Schiffs der Welt. Und wie sie in nur einer einzigen Nacht unterging.",
 "Ahoi! Ich bin Käpt'n Kurt. Heute erzähle ich dir die Geschichte der Titanic – des berühmtesten Schiffs der Welt. Und wie sie in nur einer einzigen Nacht unterging."),
("Die Titanic war damals das größte Schiff der Welt. Rund zweihundertneunundsechzig Meter lang, das sind etwa zweieinhalb Fußballfelder. Viele hielten sie für unsinkbar.",
 "Die Titanic war damals das größte Schiff der Welt. Rund 269 Meter lang – das sind etwa zweieinhalb Fußballfelder. Viele hielten sie für unsinkbar."),
("Am zehnten April neunzehnhundertzwölf legte sie in Southampton in England ab. Ihr Ziel: New York. An Bord waren rund zweitausendzweihundert Menschen, Passagiere und Besatzung.",
 "Am 10. April 1912 legte sie in Southampton in England ab. Ihr Ziel: New York. An Bord waren rund 2200 Menschen – Passagiere und Besatzung."),
("Vier Tage später fuhr sie durch den eiskalten Nordatlantik. Den ganzen Tag kamen Warnungen vor Eis. Trotzdem fuhr die Titanic mit hoher Geschwindigkeit weiter.",
 "Vier Tage später fuhr sie durch den eiskalten Nordatlantik. Den ganzen Tag kamen Warnungen vor Eis. Trotzdem fuhr die Titanic mit hoher Geschwindigkeit weiter."),
("Um dreiundzwanzig Uhr vierzig rief der Ausguck: Eisberg direkt voraus! Das Schiff versuchte noch auszuweichen. Doch es war zu spät. Der Eisberg schrammte an der Seite entlang.",
 "Um 23:40 Uhr rief der Ausguck: „Eisberg direkt voraus!“ Das Schiff versuchte noch auszuweichen. Doch es war zu spät. Der Eisberg schrammte an der Seite entlang."),
("Der Rumpf hatte sechzehn wasserdichte Abteilungen. Mit vier gefluteten hätte die Titanic noch schwimmen können. Doch fünf liefen voll Wasser. Damit war ihr Schicksal besiegelt.",
 "Der Rumpf hatte 16 wasserdichte Abteilungen. Mit vier gefluteten hätte die Titanic noch schwimmen können. Doch fünf liefen voll Wasser. Damit war ihr Schicksal besiegelt."),
("Und es gab ein weiteres Problem. An Bord waren nur zwanzig Rettungsboote, mit Platz für etwa elfhundertachtundsiebzig Menschen. Das reichte nur für gut die Hälfte. Und viele Boote fuhren halb leer davon.",
 "Und es gab ein weiteres Problem: An Bord waren nur 20 Rettungsboote – mit Platz für etwa 1178 Menschen. Das reichte nur für gut die Hälfte. Und viele Boote fuhren halb leer davon."),
("Langsam sank der Bug ins Meer. Das Heck hob sich hoch in die Luft, bis das Schiff in zwei Teile zerbrach. Um zwei Uhr zwanzig verschwand die Titanic im Ozean.",
 "Langsam sank der Bug ins Meer. Das Heck hob sich hoch in die Luft, bis das Schiff in zwei Teile zerbrach. Um 2:20 Uhr verschwand die Titanic im Ozean."),
("Das Wasser war etwa minus zwei Grad kalt. Rund fünfzehnhundert Menschen verloren in dieser Nacht ihr Leben.",
 "Das Wasser war etwa minus zwei Grad kalt. Rund 1500 Menschen verloren in dieser Nacht ihr Leben."),
("Erst gegen vier Uhr morgens erreichte das Schiff Carpathia die Unglücksstelle. Es nahm rund siebenhundert Überlebende aus den Rettungsbooten auf.",
 "Erst gegen vier Uhr morgens erreichte das Schiff Carpathia die Unglücksstelle. Es nahm rund 700 Überlebende aus den Rettungsbooten auf."),
("Danach lag das Wrack dreiundsiebzig Jahre verborgen. Erst neunzehnhundertfünfundachtzig fand ein Team um Robert Ballard die Titanic. In fast vier Kilometern Tiefe, zerbrochen in zwei Teile.",
 "Danach lag das Wrack 73 Jahre verborgen. Erst 1985 fand ein Team um Robert Ballard die Titanic – in fast vier Kilometern Tiefe, zerbrochen in zwei Teile."),
("Nach dem Unglück wurden die Regeln geändert. Seitdem muss jedes Schiff genug Rettungsboote für alle an Bord haben. So hat die Titanic die Seefahrt sicherer gemacht. Tschüss, und bis zum nächsten Mal!",
 "Nach dem Unglück wurden die Regeln geändert: Seitdem muss jedes Schiff genug Rettungsboote für alle an Bord haben. So hat die Titanic die Seefahrt sicherer gemacht. Tschüss – und bis zum nächsten Mal!"),
]
